import TshirtArticle from "../../assets/images/shop/model.jpg";
import WatchArticle from "../../assets/images/shop/model1.jpg";
import SpaceArticle from "../../assets/images/shop/model2.jpg";
import Model from "../../assets/images/shop/model3.jpg";
import { ShopArticle } from "../../app/shop/domain/core/article";
import ShopArticleSlider from "../../components/shop/slider";
import { shopStore } from "../../app/shop/store/domain/core/shop.store";
import { useRouter } from "next/router";

const ShopFeatured = () => {
  const { setSelectedArticle, getArticles } = shopStore();
  const router = useRouter();

  const openArticle = (article: ShopArticle) => {
    setSelectedArticle(article);
    getArticles();
    router.push("/shop/article");
  };

  const articles = [
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 25.3, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Vincent Lay", price: 28.3, image: WatchArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Daniel Saadia", price: 28.3, image: SpaceArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Astro", price: 98.3, image: Model.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Aiden Pearce", price: 5.3, image: SpaceArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Vincent Lay", price: 28, image: TshirtArticle.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
    new ShopArticle({name: "Daniel Saadia", price: 65, image: Model.src, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi scelerisque tortor a est ultrices, in sagittis nulla hendrerit. Curabitur congue imperdiet neque vitae pulvinar. Etiam risus neque, suscipit ac est sit amet, eleifend semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque blandit malesuada justo, fermentum commodo magna maximus sit amet. Etiam ac fringilla quam, vitae euismod ex." }),
  ];

  return (
    <ShopArticleSlider articles={articles} category={"Featured sellers"} onClick={openArticle}/>
  );
};

export default ShopFeatured;

